# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Steam
        allowPrerelease: true
      settings:
        id: Valve.Steam
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Discord
        allowPrerelease: true
      settings:
        id: Discord.Discord
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Oh-my-posh shell module for Microsoft Terminal
        allowPrerelease: true
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Google Chrome
        allowPrerelease: true
      settings:
        id: Google.Chrome
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Microsoft Office
        allowPrerelease: true
      settings:
        id: Microsoft.Office
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install latest release of Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install GitHub CLI
        allowPrerelease: true
      settings:
        id: GitHub.cli
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: VSCode
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Python (SNEKS!)
        allowPrerelease: true
      settings:
        id: Python.Python.3.13
        source: winget
        
  configurationVersion: 0.2.0